system:
  cpus: 1
  gpus: 1
  seed: 1
  
dataset:
  sample3:
    images: [
      "precomputed://file:///mnt/ceph/users/neuro/wasp_em/jwu/sample3/05_yuri_v3",
      "precomputed://file:///mnt/ceph/users/neuro/wasp_em/jwu/sample3/07_yuri_v5",
      "precomputed://file:///mnt/ceph/users/neuro/wasp_em/jwu/sample3/04_clahe"
    ]
    mask: "precomputed://file:///mnt/ceph/users/neuro/wasp_em/jwu/sample3/20_segmentation_mask"
    labels:
      training: [
        "/mnt/ceph/users/neuro/wasp_em/jwu/40_gt/13_wasp_sample3/vol_01700/label_v3.h5",
        "/mnt/ceph/users/neuro/wasp_em/jwu/40_gt/13_wasp_sample3/vol_02400/label_v1.h5",
        "/mnt/ceph/users/neuro/wasp_em/jwu/40_gt/13_wasp_sample3/vol_03290/label_v1.h5",
        "/mnt/ceph/users/neuro/wasp_em/jwu/40_gt/13_wasp_sample3/vol_03700/label_v3.h5",
        "/mnt/ceph/users/neuro/wasp_em/jwu/40_gt/13_wasp_sample3/vol_03998/label_v2.h5",
        "/mnt/ceph/users/neuro/wasp_em/jwu/40_gt/13_wasp_sample3/vol_04900/label_v1.h5",
        "/mnt/ceph/users/neuro/wasp_em/jwu/40_gt/13_wasp_sample3/vol_05250/label_v3_remove_contact.h5",
      ]
      validation: [
        "/mnt/ceph/users/neuro/wasp_em/jwu/40_gt/13_wasp_sample3/vol_04000/label_v3.h5",
        "/mnt/ceph/users/neuro/wasp_em/jwu/40_gt/13_wasp_sample3/vol_05450/label_v4_chiyip.h5",
      ]
model:
  in_channels: 1
  out_channels: 13  # first 3 are affinities, other 10 are LSDs

train:
  task: "aff+lsd"  # "aff" | "lsd" | "aff+lsd"
  num_affinities: 3
  lsds_to_affs_weight_ratio: 0.5
  iter_start: 0
  iter_stop: 1000000
  class_rebalance: false
  # batch size per GPU
  # The dataprovider should provide nGPU*batch_size batches!
  batch_size: 1
  output_dir: "./"
  patch_size: [128, 128, 128]
  learning_rate: 0.001
    #training_interval: 200
    #validation_interval: 2000
  training_interval: 2
  validation_interval: 4
